In [1]:
import pandas as pd
pd.set_option('max_rows', 500)
pd.set_option('max_columns', 500)
df = pd.read_csv('sugarcane_spatial_cluster.csv')
x1 = df[['incidencia_RSD','longitude', 'latitude', 'area','edad',
       'incidencia_LSD', 
       'NDVI', 'RH2M', 'PRECTOTCORR', 'WS2M', 'PAR', 'T2M',
       'T2M_MAX', 'T2M_MIN', 'densidad_aparente_0-30cm_mean',
       'intercambio_catiónico_0-30cm_mean', 'fraccion_gruesa_0-30cm_mean',
       'arcillas_0-30cm_mean', 'nitrogeno_0-30cm_mean', 'ph_0-30cm_mean',
       'arena_0-30cm_mean', 'limo_0-30cm_mean', 'carbono_organico_0-30cm_mean', 'cluster']]

In [2]:
df_drop=x1.drop(labels=['incidencia_RSD', 'incidencia_LSD'],axis=1)
cols = df_drop.columns.tolist()
cols.insert(0, cols.pop(cols.index('cluster')))
df_drop = df_drop.reindex(columns= cols)
df_drop

,cluster,longitude,latitude,area,edad,NDVI,RH2M,PRECTOTCORR,WS2M,PAR,T2M,T2M_MAX,T2M_MIN,densidad_aparente_0-30cm_mean,intercambio_catiónico_0-30cm_mean,fraccion_gruesa_0-30cm_mean,arcillas_0-30cm_mean,nitrogeno_0-30cm_mean,ph_0-30cm_mean,arena_0-30cm_mean,limo_0-30cm_mean,carbono_organico_0-30cm_mean
0,0,-76.38,3.24,4.87,7.03,0.78,15.50,1.24,0.85,127.93,14.60,19.01,10.63,1.35,19.37,7.23,35.10,21.30,5.83,23.07,41.80,32.77
1,0,-76.37,3.56,4.87,7.03,0.84,16.72,1.52,0.59,127.93,15.76,19.92,12.42,1.41,22.03,4.33,39.63,22.00,5.87,20.70,39.67,33.37
2,0,-76.48,3.34,4.87,7.03,0.83,16.72,1.52,0.59,127.93,15.76,19.92,12.42,1.37,20.60,4.10,41.80,25.70,5.60,22.47,35.70,38.50
3,0,-76.31,3.40,4.87,7.03,0.80,16.72,1.52,0.59,127.93,15.76,19.92,12.42,1.41,22.90,2.50,35.63,21.96,5.93,26.60,37.77,26.30
4,0,-76.30,3.26,4.87,7.03,0.60,16.72,1.52,0.59,127.93,15.76,19.92,12.42,1.34,18.53,6.03,37.20,20.22,5.73,23.70,39.17,31.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20800,0,-76.53,3.17,4.87,7.00,0.74,17.08,0.68,2.44,128.15,16.80,22.15,12.51,1.31,19.10,2.90,39.97,21.52,5.47,25.33,34.70,37.57
20801,0,-76.29,3.37,1.83,5.90,0.62,16.01,0.12,2.55,128.15,15.90,20.90,11.80,1.37,19.13,4.40,34.20,18.56,5.70,27.73,38.07,29.13
20802,0,-76.29,3.37,2.38,6.40,0.62,19.26,2.52,1.16,128.15,19.08,23.98,14.90,1.37,19.13,4.40,34.20,18.56,5.70,27.73,38.07,29.13
20803,0,-76.33,3.28,4.87,7.00,0.52,17.08,0.68,2.44,128.15,16.80,22.15,12.51,1.36,20.00,3.63,38.33,20.42,5.67,27.00,34.63,27.47
20804,0,-76.30,3.37,2.38,6.40,0.82,17.08,0.68,2.44,128.15,16.80,22.15,12.51,1.41,21.90,4.07,36.83,19.39,6.10,29.00,34.17,29.67

In [3]:
df_drop=df_drop.drop(labels=['cluster','longitude', 'latitude'],axis=1)

In [4]:
df_drop

,area,edad,NDVI,RH2M,PRECTOTCORR,WS2M,PAR,T2M,T2M_MAX,T2M_MIN,densidad_aparente_0-30cm_mean,intercambio_catiónico_0-30cm_mean,fraccion_gruesa_0-30cm_mean,arcillas_0-30cm_mean,nitrogeno_0-30cm_mean,ph_0-30cm_mean,arena_0-30cm_mean,limo_0-30cm_mean,carbono_organico_0-30cm_mean
0,4.87,7.03,0.78,15.50,1.24,0.85,127.93,14.60,19.01,10.63,1.35,19.37,7.23,35.10,21.30,5.83,23.07,41.80,32.77
1,4.87,7.03,0.84,16.72,1.52,0.59,127.93,15.76,19.92,12.42,1.41,22.03,4.33,39.63,22.00,5.87,20.70,39.67,33.37
2,4.87,7.03,0.83,16.72,1.52,0.59,127.93,15.76,19.92,12.42,1.37,20.60,4.10,41.80,25.70,5.60,22.47,35.70,38.50
3,4.87,7.03,0.80,16.72,1.52,0.59,127.93,15.76,19.92,12.42,1.41,22.90,2.50,35.63,21.96,5.93,26.60,37.77,26.30
4,4.87,7.03,0.60,16.72,1.52,0.59,127.93,15.76,19.92,12.42,1.34,18.53,6.03,37.20,20.22,5.73,23.70,39.17,31.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20800,4.87,7.00,0.74,17.08,0.68,2.44,128.15,16.80,22.15,12.51,1.31,19.10,2.90,39.97,21.52,5.47,25.33,34.70,37.57
20801,1.83,5.90,0.62,16.01,0.12,2.55,128.15,15.90,20.90,11.80,1.37,19.13,4.40,34.20,18.56,5.70,27.73,38.07,29.13
20802,2.38,6.40,0.62,19.26,2.52,1.16,128.15,19.08,23.98,14.90,1.37,19.13,4.40,34.20,18.56,5.70,27.73,38.07,29.13
20803,4.87,7.00,0.52,17.08,0.68,2.44,128.15,16.80,22.15,12.51,1.36,20.00,3.63,38.33,20.42,5.67,27.00,34.63,27.47
20804,2.38,6.40,0.82,17.08,0.68,2.44,128.15,16.80,22.15,12.51,1.41,21.90,4.07,36.83,19.39,6.10,29.00,34.17,29.67

In [5]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from advanced_pca import CustomPCA

X_std = StandardScaler().fit_transform(df_drop)

## The significant feature mask in custom_pca.py is > 5

In [6]:
# fit pca objects with option selecting only significant features
significant_pca5 = (CustomPCA(n_components=8, feature_selection='significant')
                    .fit(X_std))

# print selected features based on weights and communalities significance
print('Communalities:\n', significant_pca5.communalities_)
print('\nSelected Features:\n',
      np.asarray(df_drop.columns)[significant_pca5.get_support()])

# execute dimensionality reduction and pring dataset shapes
print('\nOriginal dataset shape:', X_std.shape)
print('Reduced dataset shape:', significant_pca5.transform(X_std).shape)

Communalities:
 [0.37816837 0.57528271 0.49250444 0.26557423 0.55984245 0.3005008
 0.71723824 0.26543826 0.29472657 0.25806455 0.25256098 0.45626918
 0.31156053 0.76503315 0.36943632 0.44132256 0.53213918 0.50616668
 0.2581708 ]

Selected Features:
 ['edad' 'PRECTOTCORR' 'PAR' 'arcillas_0-30cm_mean' 'arena_0-30cm_mean'
 'limo_0-30cm_mean']

Original dataset shape: (20805, 19)
Reduced dataset shape: (20805, 6)

In [7]:
significant_pca5

CustomPCA(feature_selection='significant')

In [8]:
variables_pca = ['edad','PRECTOTCORR', 'PAR', 'arcillas_0-30cm_mean','arena_0-30cm_mean','limo_0-30cm_mean']

In [11]:
round(df[variables_pca].describe(),2).T

,count,mean,std,min,25%,50%,75%,max
edad,20805.0,7.03,0.85,0.91,6.50,7.00,7.40,14.40
PRECTOTCORR,20805.0,4.18,6.48,0.00,0.34,1.75,5.41,57.61
PAR,20805.0,133.22,4.89,111.19,129.80,133.29,136.99,144.67
arcillas_0-30cm_mean,20805.0,37.68,2.50,26.03,36.07,37.63,39.33,49.03
arena_0-30cm_mean,20805.0,25.87,3.63,15.20,23.43,25.37,28.27,38.37
limo_0-30cm_mean,20805.0,36.44,3.57,23.50,34.30,37.00,38.90,45.90

In [10]:
ubicacion = df[['cluster','longitude','latitude']]

In [13]:
concat = pd.concat([ubicacion,df[variables_pca]], axis = 1)

In [14]:
concat

,cluster,longitude,latitude,edad,PRECTOTCORR,PAR,arcillas_0-30cm_mean,arena_0-30cm_mean,limo_0-30cm_mean
0,0,-76.38,3.24,7.03,1.24,127.93,35.10,23.07,41.80
1,0,-76.37,3.56,7.03,1.52,127.93,39.63,20.70,39.67
2,0,-76.48,3.34,7.03,1.52,127.93,41.80,22.47,35.70
3,0,-76.31,3.40,7.03,1.52,127.93,35.63,26.60,37.77
4,0,-76.30,3.26,7.03,1.52,127.93,37.20,23.70,39.17
...,...,...,...,...,...,...,...,...,...
20800,0,-76.53,3.17,7.00,0.68,128.15,39.97,25.33,34.70
20801,0,-76.29,3.37,5.90,0.12,128.15,34.20,27.73,38.07
20802,0,-76.29,3.37,6.40,2.52,128.15,34.20,27.73,38.07
20803,0,-76.33,3.28,7.00,0.68,128.15,38.33,27.00,34.63
20804,0,-76.30,3.37,6.40,0.68,128.15,36.83,29.00,34.17

In [18]:
categoricas = df[['year', 'month', 'ingenio', 'hacienda', 'area',
       'variedad', 'corte', 'lote_comercial', 'lote_semillero', 'incidencia_RSD', 'incidencia_LSD', 'prevalencia_RSD',
       'prevalencia_LSD','cluster']]

In [20]:
variables_resumidas = pd.concat([categoricas, concat], axis = 1)

In [21]:
variables_resumidas.to_csv('variables_resumidas.csv', index = False)