In [1]:
import pandas as pd

In [16]:
variables = pd.read_csv('variables_pca.csv')

In [10]:
variables1 = variables.drop(['longitude', 'latitude'], axis = 1)

In [24]:
variables_group = variables1.groupby(['cluster'])

In [46]:
tabla_resumen = variables_group.describe()

In [53]:
tabla_resumen = tabla_resumen.T

In [55]:
tabla_resumen.columns

Int64Index([-1, 0, 1, 2, 3, 4], dtype='int64', name='cluster')

In [61]:
tabla_resumen = round(tabla_resumen.rename({-1:1,0:2,1:3,2:4,3:5,4:6}, axis=1),2)

In [62]:
tabla_resumen

cluster                          5         6       5       6       5       6
edad                 count    1.00  20656.00   88.00   35.00   18.00    7.00
                     mean     6.60      7.03    6.67    6.65    6.63    7.63
                     std       NaN      0.85    0.48    0.26    0.38    0.77
                     min      6.60      0.91    5.20    5.90    6.20    7.00
                     25%      6.60      6.50    6.60    6.50    6.20    7.00
                     50%      6.60      7.00    6.70    6.60    6.85    7.50
                     75%      6.60      7.40    6.80    6.90    7.00    8.10
                     max      6.60     14.40    7.70    7.00    7.00    8.71
PRECTOTCORR          count    1.00  20656.00   88.00   35.00   18.00    7.00
                     mean     0.22      4.18    5.63    2.90    4.10    4.15
                     std       NaN      6.48    7.61    2.83    4.14    6.49
                     min      0.22      0.00    0.02    0.00    0.19    0.11
                     25%      0.22      0.34    0.39    0.53    1.53    0.25
                     50%      0.22      1.74    1.93    2.42    2.51    0.57
                     75%      0.22      5.40    6.50    4.76    3.15    7.10
                     max      0.22     57.61   27.89   10.93   12.60   13.64
PAR                  count    1.00  20656.00   88.00   35.00   18.00    7.00
                     mean   132.38    133.22  133.13  131.27  133.68  130.05
                     std       NaN      4.89    5.79    5.84    3.36    5.40
                     min    132.38    111.19  121.09  121.09  130.42  125.84
                     25%    132.38    129.80  128.02  129.19  130.42  125.89
                     50%    132.38    133.29  134.07  131.63  132.88  125.94
                     75%    132.38    136.99  137.66  134.17  136.94  134.84
                     max    132.38    144.67  142.13  142.13  138.06  137.09
arcillas_0-30cm_mean count    1.00  20656.00   88.00   35.00   18.00    7.00
                     mean    37.27     37.69   37.52   34.95   39.27   37.71
                     std       NaN      2.51    1.23    0.11    0.00    1.50
                     min     37.27     26.03   35.17   34.93   39.27   36.83
                     25%     37.27     36.07   36.55   34.93   39.27   36.83
                     50%     37.27     37.60   37.70   34.93   39.27   36.83
                     75%     37.27     39.37   38.50   34.93   39.27   38.36
                     max     37.27     49.03   38.50   35.57   39.27   39.90
arena_0-30cm_mean    count    1.00  20656.00   88.00   35.00   18.00    7.00
                     mean    27.23     25.87   25.96   27.26   28.27   30.71
                     std       NaN      3.64    1.67    0.46    0.00    1.01
                     min     27.23     15.20   24.80   25.77   28.27   29.23
                     25%     27.23     23.43   24.80   27.40   28.27   30.26
                     50%     27.23     25.33   25.25   27.40   28.27   31.30
                     75%     27.23     28.27   25.73   27.40   28.27   31.30
                     max     27.23     38.37   29.67   27.47   28.27   31.30
limo_0-30cm_mean     count    1.00  20656.00   88.00   35.00   18.00    7.00
                     mean    35.43     36.45   36.53   37.76   32.47   31.58
                     std       NaN      3.58    1.06    0.50    0.00    0.49
                     min     35.43     23.50   34.10   36.93   32.47   30.87
                     25%     35.43     34.30   36.60   37.63   32.47   31.37
                     50%     35.43     37.03   36.73   37.63   32.47   31.87
                     75%     35.43     38.93   36.73   37.63   32.47   31.87
                     max     35.43     45.90   39.77   39.33   32.47   31.87